---
title: "Homework 3"
author: ~
date: '2020-09-09'
slug: "hw03"
categories: [homework]
tags: [week03]
draft: false
toc: true
---

```{r, setup, echo=TRUE}
library(tidyverse)

d <- read_csv("../../static/data/chris_names_wide.csv")

d_l <- d %>%
  pivot_longer(-year, names_to = "sex")

p1 <- ggplot(d_l, aes(x=year, y=value, colour = sex)) +
  geom_line()
print(p1)

p2 <- ggplot(d_l, aes(x=year, y=value, colour = sex)) +
  geom_point() +
  geom_smooth(method = "loess")
print(p2)

p3 <- ggplot(d_l, aes(x=sex, y=value)) +
  geom_boxplot()
print(p3)

#ggsave("../../static/plots/chris_line.png", p1, height = 3, width = 4, units = "in", dpi = 300)
#ggsave("../../static/plots/chris_smooth.png", p2, height = 3, width = 4, units = "in", dpi = 3)
#ggsave("../../static/plots/chris_box.png", p3, height = 3, width = 4, units = "in", dpi = 300)

```


This homework, as well as homework 2, is due Wednesday Sept 16. Lecture notes coming ASAP.

<!--more-->

# Input / Output

Use one of the [**readr**](https://readr.tidyverse.org/) functions (`read_csv()`, `read_delim()`, etc), read in either:

* Some of your own data, or
* The .csv file [here](data/chris_data_wide.csv). This is a subset of the *babynames* dataset, which lists the number of babies registered with the US Social Security Administration by year, sex, and name. I have filtered it to only include babies named "Chris" and reformatted it. The `male` and `female` columns indicate numbers of male and female children, respectively. 

Be sure to check the check the Data Import Cheat Sheet [here](https://rstudio.com/resources/cheatsheets/). 

Save the data file with a logical file name to a new directory, `reproducible_data_analysis/data`.

# Wide vs long (tidy) data

Convert your data to long (tidy) format. For the `chris_data_wide` dataset, that means you should have a column for the year, a column for the number of babies, and a column for the sex of the baby (male vs female). 

You will want to use the `pivot_wider()` function. Check the *Reshape Data* section of the [Data Import Cheat Sheet](https://rstudio.com/resources/cheatsheets/) for tips. 

# Plotting with ggplot2

If you used the `chris_data_wide` dataset, create the following plots using **ggplot2**:

* A line plot with year on the x axis, the number of babies on the y axis, and a different color for each sex
* A plot with the same axes, but with a "loess"-smoothed line representing the data
* A boxplot with sex on the x axis and the number of people with that name on the y-axis.

If you used your own data, use **ggplot2** to make 3 plots that show the data in different ways.

